version: "3"

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: on-failure
    expose:
      - "3306"
    networks:
      - inception
    env_file:
     - .env
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: on-failure
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
     - wordpress:/var/www/html
    expose:
      - "9000"

  
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    env_file:
      - .env
    links:
      - wordpress

networks:
  inception:
    driver: bridge 

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/qdenizar/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/qdenizar/data/mariadb'
