version: "3"

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    restart: unless-stopped
    expose:
      - "3306"
    networks:
      - inception
    #Attache le conteneur au réseau inception
    env_file:
     - .env
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    restart: on-failure
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:  
     - wordpress:/var/www
    expose:
      - "9000"

  
  nginx:
    container_name: nginx
    build: requirements/nginx
    restart: on-failure
    volumes:
      - wordpress:/var/www/
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env
    ports:
      - "443:443"

networks:
  inception:
    driver: bridge 

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/qdenizar/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/qdenizar/data/mariadb'
      #"bind" lie le chemin spécifié sur l'hôte (/home/qdenizar/data/mariadb)
      # au chemin du volume dans le conteneur.
