version: "3"

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: on-failure
    ports:
      - 9090:3306
    networks:
      - inception
    env_file:
     - .env
    #volumes:
    #  - mariadb_data: /var/lib/mysql
    volumes:
      - type: volume
        source: mariadb_data
        target: /var/lib/mysql

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: on-failure
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env
   # volumes:
    #  - wordpress_data: /var/www/html
    volumes:
    - type: volume
      source: wordpress_data
      target: /var/www/html
  
  nginx:
    container_name: nginx
    image: nginx
    restart: on-failure
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - 8080:80
      - 8443:443
    env_file:
      - .env
    #volumes:
     # - nginx_config: /etc/nginx/conf.d
    volumes:
    - type: volume
      source: nginx_config
      target: /etc/nginx/conf.d

    links:
      - wordpress

networks:
  inception:
    driver: bridge 

volumes:
  mariadb_data:
  wordpress_data:
  nginx_config:
